### PR TITLE
refactor: memozie using use-deep-compare

### PR DESCRIPTION
**Pull request by LufyCZ**
#197

### CODE REVIEW

**Review by c-ehrlich — APPROVED** [review]
The bundlephobia number is inaccurate as it doesn't consider that Remeda treeshakes. But it's probably still better not to ship remeda as many people use bundlephobia to judge packages.

Thanks for the PR :)

**Review by c-ehrlich — CHANGES_REQUESTED** [review]
revoking approval as e2e is failing - issue seems to be on our side, but want to hold off on merging for now. will take a look at the tests tomorrow.

**Comment by LufyCZ** [comment]
> The bundlephobia number is inaccurate as it doesn't consider that Remeda treeshakes. But it's probably still better not to ship remeda as many people use bundlephobia to judge packages.
> 
> Thanks for the PR :)



> The bundlephobia number is inaccurate as it doesn't consider that Remeda treeshakes. But it's probably still better not to ship remeda as many people use bundlephobia to judge packages.
> 
> Thanks for the PR :)

I got here by looking at our bundles, it looks like the whole remeda package is getting included. Could be a misconfiguration on our side though.

image

**Review by c-ehrlich — APPROVED** [review]
sorry for the delay. still need to get the e2e situation worked out in CI, but happy to merge :)

**Pull request merged**
