### PR TITLE
Guard against navigator.sendBeacon errors

### PR DESCRIPTION
**Pull request by maxkostow**
See https://github.com/vercel/next.js/pull/26601 and https://xgwang.me/posts/you-may-not-know-beacon/#it-may-throw-error%2C-be-sure-to-catch

### CODE REVIEW

**Review by schehata — APPROVED** [review]
Legit, thanks for your contribution <3

**Comment by schehata** [comment]
@maxkostow we have updated the CI workflow to run for external PRs as well. Now one of the checks is failing, can you take a look?

**Comment by maxkostow** [comment]
Updated the test

**Comment by schehata** [comment]
@maxkostow thanks man, the new version `v0.12.1` is now released 🥳

**Pull request merged**
